# add at the top of your ~/.zshenv:
# export JILION_PATH=<path to your Jilion projects dir.>
# . $JILION_PATH/Products/setup/dotfiles/zshenv

. $JILION_PATH/Products/setup/dotfiles/zsh/env
. $JILION_PATH/Products/setup/dotfiles/zsh/config
. $JILION_PATH/Products/setup/dotfiles/zsh/aliases

# Set Apple Terminal.app resume directory
if [[ $TERM_PROGRAM == "Apple_Terminal" ]] && [[ -z "$INSIDE_EMACS" ]] {
  function chpwd {
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
  }

  chpwd
}
