# add at the top of your ~/.bashrc
# export JIME_SETUP_PATH=<path to your jime_setup git repo.>
# export JIME_CODE_PATH=<path to your jime code dir.>
# export JILION_PATH=<path to your jilion projects dir.>
# 
# . $JIME_SETUP_PATH/shell/bashrc

. $JIME_SETUP_PATH/shell/bash/aliases
. $JIME_SETUP_PATH/shell/bash/config
. $JIME_SETUP_PATH/shell/bash/env